//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTienda
{


    public partial class LoginUsuario
    {

        /// <summary>
<<<<<<< HEAD:SoftTienda/Home.Master.designer.cs
        /// head control.
=======
        /// Control lblUsuario.
>>>>>>> main:SoftTienda/LoginUsuario.aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblUsuario;

        /// <summary>
<<<<<<< HEAD:SoftTienda/Home.Master.designer.cs
        /// TopBar control.
=======
        /// Control lblContraseña.
>>>>>>> main:SoftTienda/LoginUsuario.aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD:SoftTienda/Home.Master.designer.cs
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TopBar;

        /// <summary>
        /// Footer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder Footer;
=======
        protected global::System.Web.UI.WebControls.Label lblContraseña;
>>>>>>> main:SoftTienda/LoginUsuario.aspx.designer.cs
    }
}
